### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by satadhi** [satadhi/amazon-graphql-service#1]
### Auth tasks list

- [ ] Create a login URL
- [ ] understand the concept of repository pattern (LLD)
- [ ] backend initial design
